import { NextResponse } from "next/server";

type Finding = {
  nodeId: string;
  nodeLabel: string;
  severity: "high" | "medium" | "low";
  message: string;
};

type Body = {
  token: string;
  owner: string;
  repo: string;
  findings: Finding[];
  target: string;
};

const SEV_LABEL: Record<string, { name: string; color: string; description: string }> = {
  high:   { name: "severity: high",   color: "d73a4a", description: "High-severity finding from UI audit" },
  medium: { name: "severity: medium", color: "e4a000", description: "Medium-severity finding from UI audit" },
  low:    { name: "severity: low",    color: "0e8a16", description: "Low-severity finding from UI audit" },
};

async function ensureLabel(
  token: string,
  owner: string,
  repo: string,
  severity: string
): Promise<void> {
  const lbl = SEV_LABEL[severity];
  if (!lbl) return;
  await fetch(`https://api.github.com/repos/${owner}/${repo}/labels`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ name: lbl.name, color: lbl.color, description: lbl.description }),
  });
  // 422 = label already exists — that's fine
}

export async function POST(req: Request) {
  let body: Body;
  try { body = await req.json(); }
  catch { return NextResponse.json({ error: "Invalid JSON" }, { status: 400 }); }

  const { token, owner, repo, findings, target } = body;
  if (!token || !owner || !repo) {
    return NextResponse.json({ error: "token, owner, and repo are required" }, { status: 400 });
  }
  if (!findings?.length) {
    return NextResponse.json({ error: "No findings to export" }, { status: 400 });
  }

  const created: string[] = [];
  const failed: string[] = [];

  // Ensure labels exist (best-effort)
  const severities = [...new Set(findings.map((f) => f.severity))];
  await Promise.all(severities.map((s) => ensureLabel(token, owner, repo, s)));

  for (const f of findings) {
    const lbl = SEV_LABEL[f.severity];
    const issueBody = [
      `**Screen:** ${f.nodeLabel}`,
      `**Severity:** ${f.severity.toUpperCase()}`,
      `**Target:** \`${target}\``,
      "",
      "---",
      "",
      f.message,
      "",
      "_Generated by [UI Flow Auditor](https://github.com/techrhoohm/ui-flow-auditor-agent)_",
    ].join("\n");

    const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: `[${f.severity.toUpperCase()}] ${f.nodeLabel}: ${f.message.slice(0, 80)}`,
        body: issueBody,
        labels: lbl ? [lbl.name] : [],
      }),
    });

    if (res.ok) {
      const data = await res.json() as { html_url: string };
      created.push(data.html_url);
    } else {
      failed.push(f.message.slice(0, 60));
    }
  }

  return NextResponse.json({ created, failed });
}
