import { NextResponse } from "next/server";

type Finding = {
  nodeLabel: string;
  severity: "high" | "medium" | "low";
  message: string;
};

type Totals = {
  screens: number;
  high: number;
  medium: number;
  low: number;
  total: number;
};

type Body = {
  webhookUrl: string;
  title: string;
  target: string;
  totals: Totals;
  topFindings: Finding[];
};

export async function POST(req: Request) {
  let body: Body;
  try { body = await req.json(); }
  catch { return NextResponse.json({ error: "Invalid JSON" }, { status: 400 }); }

  const { webhookUrl, title, target, totals, topFindings } = body;
  if (!webhookUrl) {
    return NextResponse.json({ error: "webhookUrl is required" }, { status: 400 });
  }

  const severityIcon = (s: string) =>
    s === "high" ? ":red_circle:" : s === "medium" ? ":large_orange_circle:" : ":large_yellow_circle:";

  const findingBlocks = topFindings.slice(0, 5).map((f) => ({
    type: "section",
    text: {
      type: "mrkdwn",
      text: `${severityIcon(f.severity)} *${f.nodeLabel}* — ${f.message}`,
    },
  }));

  const payload = {
    blocks: [
      {
        type: "header",
        text: { type: "plain_text", text: `UI Audit: ${title}`, emoji: true },
      },
      {
        type: "section",
        text: { type: "mrkdwn", text: `*Target:* \`${target}\`` },
      },
      { type: "divider" },
      {
        type: "section",
        fields: [
          { type: "mrkdwn", text: `*Screens*\n${totals.screens}` },
          { type: "mrkdwn", text: `*Total findings*\n${totals.total}` },
          { type: "mrkdwn", text: `:red_circle: *High*\n${totals.high}` },
          { type: "mrkdwn", text: `:large_orange_circle: *Medium*\n${totals.medium}` },
        ],
      },
      ...(findingBlocks.length > 0
        ? [{ type: "divider" }, { type: "section", text: { type: "mrkdwn", text: "*Top findings*" } }, ...findingBlocks]
        : []),
      { type: "divider" },
      {
        type: "context",
        elements: [
          {
            type: "mrkdwn",
            text: `_Generated by UI Flow Auditor · ${new Date().toLocaleString()}_`,
          },
        ],
      },
    ],
  };

  const slackRes = await fetch(webhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!slackRes.ok) {
    const text = await slackRes.text();
    return NextResponse.json({ error: `Slack returned ${slackRes.status}: ${text}` }, { status: 502 });
  }

  return NextResponse.json({ ok: true });
}
